# Example usage of LatentSDE
This notebook is intended to give a quick overview of how to use the functionality provided by this package.

In [46]:
# installs
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt

## Querying MIMIC-IV in Python
Once you have access to the MIMIC-IV dataset in Google BigQuery, you are ready to start querying in Python. Pandas gbq is a package which allows us to query the MIMIC-IV dataset hosted on Google BigQuery and store the result in a pandas dataframe. The following code is a toy example of how to write and store the results of queries.

In [1]:
from pandas.io import gbq

project = "mimic-380019" # replace with your Google Cloud project ID

# query first 10 rows of the vitalsign table
query = """
    SELECT *
    FROM physionet-data.mimiciv_derived.vitalsign
    LIMIT 100
    """

data = gbq.read_gbq(query, project_id=project) # this will prompt you to provide the account info associated w 

data.head(10)

,subject_id,stay_id,charttime,heart_rate,sbp,dbp,mbp,sbp_ni,dbp_ni,mbp_ni,resp_rate,temperature,temperature_site,spo2,glucose
0,16255318,35069090,2146-03-22 18:00:00,99.0,127.0,79.5,92.0,123.0,60.0,74.0,34.0,None,None,100.0,NaN
1,17601166,35276354,2175-11-23 00:00:00,82.0,177.0,89.0,107.0,177.0,89.0,107.0,36.0,37.440000000,Oral,96.0,123.0
2,12490757,35100581,2149-04-20 05:00:00,97.0,95.0,27.0,43.0,95.0,27.0,43.0,36.0,37.670000000,Axillary,97.0,NaN
3,11594102,33957854,2175-08-08 12:00:00,88.0,89.5,49.5,61.5,95.0,54.0,63.0,13.5,36.890000000,Oral,94.0,NaN
4,16337794,36877509,2182-02-13 04:00:00,79.0,147.0,88.0,96.0,147.0,88.0,96.0,27.5,37.110000000,Oral,95.0,NaN
5,11264212,38912610,2144-10-22 02:00:00,48.0,96.0,48.5,62.0,97.0,48.0,59.0,8.0,None,None,100.0,NaN
6,11267564,34685399,2159-03-14 08:00:00,95.0,172.0,91.0,116.0,NaN,NaN,NaN,25.5,37.720000000,Oral,100.0,NaN
7,18240093,33702630,2157-07-20 01:00:00,106.0,168.0,87.0,111.0,NaN,NaN,NaN,38.0,None,None,100.0,NaN
8,15944907,33478333,2156-01-31 21:09:00,NaN,133.0,110.0,115.0,133.0,110.0,115.0,7.0,None,None,NaN,NaN
9,11666315,31087546,2177-06-27 04:00:00,66.0,80.0,36.0,39.0,80.0,36.0,39.0,23.5,36.670000000,Oral,NaN,98.0

In [27]:
len(data['stay_id'].unique())

10

## Latent SDE toy example
Informatively sampled sin data

In [45]:
import os

os.listdir('data')

['mimic_data.py', 'toy_data.py', '__pycache__']

In [48]:
from data.toy_data import InformativeSinData

dataset = InformativeSinData(t_size=25, n_samples=10)
dataset[0]

ImportError: cannot import name 'InformativeSinData' from 'data.toy_data' (c:\Users\Owner\OneDrive\Desktop\Sepsis\code\data\toy_data.py)